version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - mynetwork
    restart: always
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OPTS: "-Djava.net.preferIPv4Stack=true"
    networks:
      - mynetwork
    depends_on:
      zookeeper:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka:9092"]
      interval: 5s
      timeout: 10s
      retries: 30

  kafka_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    image: kafka_consumer:1.0
    environment:
      KAFKA_BROKER: kafka:9092
      MODE: ${MODE:-local}
    command: python /workspace/server_consumer/kafka_consumer.py
    networks:
      - mynetwork
    depends_on:
      kafka:
        condition: service_healthy
    restart: always

  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_server:1.0
    environment:
      KAFKA_BROKER: kafka:9092
      MODE: ${MODE:-local}
      ENV_PAGE: tallas2
    command: python /workspace/server_consumer/flask_server.py
    networks:
      - mynetwork
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "5000:5000"

  tensorboard:
    image: tensorflow/tensorflow:latest
    command: tensorboard --logdir=/workspace/runs --host=0.0.0.0 --port=6006
    volumes:
      - /workspace/code/bachelor_degree/runs:/workspace/code/bachelor_degree/runs
    ports:
      - "6006:6006"
    networks:
      - mynetwork
    restart: always

volumes:
  kafka_data:

networks:
  mynetwork:
    driver: bridge
