learning_parameters:
  learning_rate: 0.00025
  discount_factor: 0.99
  train_epochs: 5
  replay_memory_size: 10000
  batch_size: 64
  test_episodes_per_epoch: 100
  frame_repeat: 12
  learning_steps_per_epoch: 1000

env_parameters:
  resolution: [30, 45]
  episodes_to_watch: 10

meta_parameters:
  out_model_file: "weights/model-doom.pth"
  save_model: True
  load_model: False
  skip_learning: False

doom_cfg_path: "/workspace/code/ViZDoom/scenarios/basic.cfg"


  
