learning_parameters:
  learning_rate: 0.003
  discount_factor: 0.96
  train_epochs: 20
  replay_memory_size: 100000
  batch_size: 128
  test_episodes_per_epoch: 100
  frame_repeat: 96
  learning_steps_per_epoch: 5000
  weight_decay: 0.007

env_parameters:
  resolution: [120, 130]
  episodes_to_watch: 10

meta_parameters:
  out_model_file: "weights/transformer_map10.pth"
  save_model: True
  load_model: False
  skip_learning: False

doom_cfg_path: "scenarios/basic.cfg"


  
