learning_parameters:
  learning_rate: 0.003
  discount_factor: 0.96
  train_epochs: 10
  replay_memory_size: 10000
  batch_size: 64
  test_episodes_per_epoch: 100000
  frame_repeat: 48
  learning_steps_per_epoch: 100
  weight_decay: 0.99

env_parameters:
  resolution: [30, 45]
  episodes_to_watch: 10

meta_parameters:
  out_model_file: "weights/model-doom.pth"
  save_model: True
  load_model: False
  skip_learning: False

doom_cfg_path: "/workspace/code/ViZDoom/scenarios/defend_the_center.cfg"


  
