learning_parameters:
  learning_rate_policy: 0.0002              # Скорость обучения модели
  learning_rate_value: 0.0001               # Скорость обучения модели
  discount_factor: 0.95              # Коэффициент дисконтирования будущих наград
  learning_steps: 5000000
  validate_fold: 5                  # Количество эпох для обучения
  batch_size: 128                    # Размер батча для оптимизатора
  test_episodes_per_epoch: 60        # Количество эпизодов для тестирования на каждой эпохе
  frame_repeat: 96                   # Количество кадров, повторяемых для каждого действия
  weight_decay: 0.007                # Коэффициент регуляризации весов
  hidden_dim: 512                    # Размерность скрытого слоя нейронной сети
  evaluate_every: 3                  # Частота оценки модели (через каждые N эпох)
  window_size: 100                   # Размер окна для усреднения метрик
  channels: 3                        # Количество каналов во входных данных

ppo_parameters:
  epoch: 7
  clip_param: 5.0                    # Параметр обрезки для PPO
  lambda_intrinsic: 0.8              # Коэффициент для внутреннего вознаграждения
  entropy_coef: 0.9                  # Коэффициент энтропии для исследования
  clip_epsiolon: 0.5                 # Порог обрезки для значений, чтобы избежать больших скачков
  embedding_dim: 144                 # Размерность эмбеддингов в модели
  num_heads: 12                       # Количество голов в многоголовой механизме внимания
  num_layers: 10                      # Число слоев в трансформер-блоке
  mlp_dim: 512                       # Размерность слоя MLP в трансформере
  patch_size: 10                     # Размер патча для разделения входных данных
  dropout_rate: 0.1                  # Вероятность dropout для регуляризации
  ex_loss: 0.0                       # Дополнительный коэффициент потерь (если есть специфичные потери)

env_parameters:
  resolution: [120, 130]             # Размер экрана (высота и ширина)
  fps: 20                            # Число кадров в секунду