learning_parameters:
  learning_rate: 0.003               # Скорость обучения модели
  discount_factor: 0.96              # Коэффициент дисконтирования будущих наград
  train_epochs: 50                  # Количество эпох для обучения
  replay_memory_size: 2500          # Размер буфера для хранения опыта
  batch_size: 256                    # Размер батча для оптимизатора
  test_episodes_per_epoch: 300        # Количество эпизодов для тестирования на каждой эпохе
  frame_repeat: 96                   # Количество кадров, повторяемых для каждого действия
  learning_steps_per_epoch: 2000        # Количество шагов обучения за каждую эпоху
  weight_decay: 0.007                # Коэффициент регуляризации весов
  hidden_dim: 512                    # Размерность скрытого слоя нейронной сети
  evaluate_every: 2                  # Частота оценки модели (через каждые N эпох)
  window_size: 100                   # Размер окна для усреднения метрик
  channels: 3                        # Количество каналов во входных данных

ppo_parameters:
  clip_param: 1.0                    # Параметр обрезки для PPO
  lambda_intrinsic: 0.8              # Коэффициент для внутреннего вознаграждения
  entropy_coef: 0.8                  # Коэффициент энтропии для исследования
  clip_epsiolon: 0.3                 # Порог обрезки для значений, чтобы избежать больших скачков
  embedding_dim: 144                 # Размерность эмбеддингов в модели
  num_heads: 12                       # Количество голов в многоголовой механизме внимания
  num_layers: 10                      # Число слоев в трансформер-блоке
  mlp_dim: 512                       # Размерность слоя MLP в трансформере
  patch_size: 10                     # Размер патча для разделения входных данных
  dropout_rate: 0.1                  # Вероятность dropout для регуляризации
  ex_loss: 0.0                       # Дополнительный коэффициент потерь (если есть специфичные потери)

env_parameters:
  resolution: [120, 130]             # Размер экрана (высота и ширина)
  fps: 15                            # Число кадров в секунду

doom_cfg_path: "scenarios/basic.cfg"  # Путь к файлу конфигурации Doom
